import { Container, Header, Footer, SectionLabel } from "@/components/site";
import { ProjectPoster } from "@/components/poster-placeholder";
import type { Project } from "@/data/projects";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export function ProjectPage({ project }: { project: Project }) {
  return <><Header/><main><section className="grid-bg border-b border-white/5 py-20"><Container><Link href="/#work" className="inline-flex items-center gap-2 text-sm text-muted hover:text-text"><ArrowLeft size={15}/>Back to work</Link><div className="mt-12 max-w-5xl"><div className="font-mono text-xs tracking-[.16em] text-cyan">{project.index} / {project.eyebrow}</div><h1 className="mt-4 text-5xl font-bold tracking-tight sm:text-7xl">{project.name}</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-muted">{project.summary}</p><div className="mt-8 grid gap-5 border-y border-line py-6 sm:grid-cols-3"><div><div className="font-mono text-xs text-dim">ROLE</div><div className="mt-1">{project.role}</div></div><div><div className="font-mono text-xs text-dim">PERIOD</div><div className="mt-1">{project.period}</div></div><div><div className="font-mono text-xs text-dim">PLATFORM</div><div className="mt-1">Web · Mobile · Backend</div></div></div></div><ProjectPoster slug={project.slug} name={project.name} className="mt-10"/></Container></section>
  <section className="py-20"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionLabel>Overview</SectionLabel><h2 className="text-3xl font-bold">What I worked on</h2></div><div><ul className="space-y-4 text-muted">{project.highlights.map(h=><li key={h} className="rounded-xl border border-line bg-panel p-5">{h}</li>)}</ul></div></div></Container></section>
  <section className="border-y border-white/5 bg-panel/40 py-20"><Container><SectionLabel>System architecture</SectionLabel><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{project.architecture.map((x,i)=><div key={x} className="rounded-xl border border-line bg-panel p-5"><div className="font-mono text-xs text-dim">NODE {String(i+1).padStart(2,'0')}</div><div className="mt-3 font-medium">{x}</div></div>)}</div></Container></section>
  <section className="py-20"><Container><SectionLabel>Engineering decisions</SectionLabel><div className="space-y-6">{project.decisions.map(d=><article key={d.title} className="rounded-2xl border border-line bg-panel p-7"><h3 className="text-2xl font-semibold">{d.title}</h3><div className="mt-6 grid gap-6 md:grid-cols-3"><div><div className="font-mono text-xs text-cyan">PROBLEM</div><p className="mt-2 text-sm leading-6 text-muted">{d.problem}</p></div><div><div className="font-mono text-xs text-cyan">DECISION</div><p className="mt-2 text-sm leading-6 text-muted">{d.decision}</p></div><div><div className="font-mono text-xs text-cyan">WHY</div><p className="mt-2 text-sm leading-6 text-muted">{d.why}</p></div></div></article>)}</div></Container></section>
  <section className="border-t border-white/5 py-20"><Container><SectionLabel>Technology</SectionLabel><div className="flex flex-wrap gap-2">{project.stack.map(s=><span key={s} className="rounded-full border border-line bg-panel px-3 py-1.5 font-mono text-xs text-muted">{s}</span>)}</div></Container></section>
  </main><Footer/></>;
}
