import { Container, Footer, Header, SectionLabel } from "@/components/site";
import { Download } from "lucide-react";

export default function ResumePage() {
  return <><Header/><main className="py-16 sm:py-24"><Container><div className="mx-auto max-w-4xl">
    <SectionLabel>Resume</SectionLabel>
    <div className="border-b border-line pb-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-4xl font-bold sm:text-5xl">Prince John Gandollas</h1><p className="mt-2 text-lg text-muted">Junior Full-Stack Engineer</p><p className="mt-3 text-sm text-muted">Binangonan, Rizal, Philippines · +63 976 134 4061 · pgandollas@gmail.com</p></div><a href="/Prince_John_Gandollas_Resume.pdf" download className="inline-flex shrink-0 items-center gap-2 rounded-full border border-line px-5 py-3 text-sm font-semibold transition hover:-translate-y-0.5 hover:border-cyan/70 hover:text-cyan"><Download size={16}/> Download PDF</a></div></div>
    <section className="py-8"><h2 className="text-xl font-semibold">Professional Summary</h2><p className="mt-3 leading-7 text-muted">Junior Full-Stack Engineer with 2+ years of hands-on experience building, scaling, and deploying production web and mobile systems. Experience spans multi-tenant POS and booking platforms, marketplace applications, offline-first workflows, RBAC/RLS, payments, APIs, and cloud deployment using TypeScript, Next.js, React Native (Expo), NestJS, Supabase, Firebase, PostgreSQL, MongoDB, and GraphQL.</p></section>
    <section className="border-t border-line py-8"><h2 className="text-xl font-semibold">Technical Skills</h2><div className="mt-4 grid gap-4 text-sm text-muted sm:grid-cols-2"><p><strong className="text-text">Languages & Frontend:</strong> TypeScript, JavaScript, SQL, HTML5, CSS3, React, Next.js, React Native, Expo, Tailwind CSS</p><p><strong className="text-text">Backend & Data:</strong> Node.js, Express.js, NestJS, Deno, GraphQL, REST APIs, PostgreSQL, SQLite, MongoDB, Supabase, Firebase</p><p><strong className="text-text">Cloud & Delivery:</strong> Google Cloud Platform, Vercel, EAS Build, EAS Update, Git, GitHub, GitHub Actions, Electron</p><p><strong className="text-text">Architecture & Integrations:</strong> Multi-Tenant Architecture, RBAC, RLS, Offline-First Sync, Webhooks, Idempotency, Xendit, Google Maps API, ESC/POS, Custom Expo Modules</p></div></section>
    <section className="border-t border-line py-8"><h2 className="text-xl font-semibold">Software Engineering Experience</h2><div className="mt-5 space-y-7 text-sm text-muted"><div><h3 className="text-base font-semibold text-text">Junior Full-Stack Engineer · FINDXNY OS</h3><p>May 2026 – Jul 2026</p><p className="mt-2 leading-6">Multi-tenant POS and booking platform across Next.js, Expo, Supabase, PostgreSQL, Deno Edge Functions, Xendit, offline SQLite sync, and ESC/POS integrations.</p></div><div><h3 className="text-base font-semibold text-text">Junior Full-Stack Engineer · Lalaba</h3><p>Oct 2025 – Aug 2026</p><p className="mt-2 leading-6">Multi-role laundry marketplace using NestJS, GraphQL, MongoDB, React Native, Next.js, Firebase, Xendit, Google Maps, and Google Cloud.</p></div><div><h3 className="text-base font-semibold text-text">Junior Full-Stack Engineer · Athlete Central</h3><p>May 2025 – Sept 2025</p><p className="mt-2 leading-6">Sports facility booking platform using Next.js, React Native, Electron, Firebase, TypeScript, and shared scheduling/pricing logic.</p></div></div></section>
    <section className="border-t border-line py-8"><h2 className="text-xl font-semibold">Additional Experience</h2><div className="mt-4 space-y-4 text-sm text-muted"><p><strong className="text-text">Special Science Teacher I · Department of Education</strong><br/>Apr 2021 – Apr 2025 · Teach programming, web development, Science, and Mathematics.</p><p><strong className="text-text">Biomedical Engineer · Iraseth Pharma Inc.</strong><br/>Dec 2019 – Mar 2021 · Preventive maintenance, troubleshooting, repair, and technical support for biomedical equipment.</p></div></section>
    <section className="border-t border-line py-8"><h2 className="text-xl font-semibold">Education & Training</h2><div className="mt-4 space-y-2 text-sm text-muted"><p>Bachelor of Science in Electronics Engineering — University of Rizal System, Apr 2019</p><p>Full-Stack Web Development (MERN) — Zuitt Tech Program, Jan–Apr 2025</p></div></section>
  </div></Container></main><Footer/></>;
}
